### ISSUE TITLE
Publish to LuaRocks?

### ISSUE THREAD

**Issue by unindented** [kyleconroy/lua-state-machine#16]
It'd be awesome to have this package on LuaRocks, so that I can depend on it without having to copy files manually...

**Comment by kyleconroy** [comment]
Sure, can you point me to a guide? I've never done it

**Comment by unindented** [comment]
Sure, the official guide is pretty good: https://github.com/keplerproject/luarocks/wiki/Creating-a-rock

You can also look at any package from [LuaRocks](https://luarocks.org/) that's hosted on GitHub, and peek at their `rockspec` (e.g. <https://github.com/kikito/ansicolors.lua>).

**Comment by kyleconroy** [comment]
Welp, I was going to do it, but it looks like you already beat me to it
