### ISSUE TITLE
 'Asynchronous State Transitions' hasn't been implemented yet?

### ISSUE THREAD

**Issue by padicao2010** [kyleconroy/lua-state-machine#17]
I check the source code, and can't find anything about  'Asynchronous State Transitions'.

No machine.ASYNC, no machine.transition.

Readme is cheating me.

**Comment by kyleconroy** [comment]
see https://github.com/kyleconroy/lua-state-machine/pull/19

**Comment by kyleconroy** [comment]
Now it's merged \o/
