### ISSUE TITLE
State does not change back to initial with 3-way omnidirectional non-wildcard state machine

### ISSUE THREAD

**Issue by 0tt** [kyleconroy/lua-state-machine#20]
```lua
local m = statemachine.create{
    initial = "idle",
    events = {
        {name = "one", from = {"idle", "two"}, to = "one"},
        {name = "two", from = {"one", "idle"}, to = "two"},
        {name = "idle", from = {"one, two"}, to = "idle"},
    }
}
print("idle", m.current)
m:one()
print("one", m.current)
m:idle()
print("idle", m.current)
```
produces output:
```
idle    idle
one     one
idle    one
```

What's going on here? I've tried changing the event names to be different to the states they transition to, but I'm still having this problem.

**Comment by 0tt** [comment]
Using a wildcard works.

**Comment by treamology** [comment]
In the idle event, you're missing a set of quotation marks that would be separating the two from events. "one, two" should be "one", "two". Fixing that produces the correct output for me.
