### ISSUE TITLE
Clean example

### ISSUE THREAD

**Issue by crysan** [kyleconroy/lua-state-machine#21]
Hi!

Can you make an example of the work for the state-machine state hero
1. Stand
2. Move (left, right)
3. Jump on the spot
4. Move to the left and Jump 
5. Move to the right and Jump  
6. Death

I would have really helped this example to understand the state-machine.
Thank!

**Comment by kyleconroy** [comment]
I’d be happy to, but I’m going to need more information from you before I
can create an example. Specifically, you need to design a [state diagram](
https://en.wikipedia.org/wiki/State_diagram) for your hero. Without that
information, it’s not clear how to design the system.

**Comment by crysan** [comment]
And it is possible in the simplest case, at least the movement?

```
Player = {}

function Player:load()
	self.img     = love.graphics.newImage("src/player.png")
	self.w       = self.img:getWidth()
	self.h       = self.img:getHeight()
	self.x       = 0
	self.y       = screenHeight - mapHeight - self.h/2
	self.speed   = 170
	self.mass   = 1
	self.bullets = {}
	self.angle   = 0
	
	self.ground = self.y
 	self.y_velocity = 0 
 	self.jump_height = -200 
	self.gravity = -500 
end

function Player:update(dt)
	if love.keyboard.isDown('right') or love.keyboard.isDown('d') then
		self.x = self.x + self.speed/self.mass * dt
	elseif love.keyboard.isDown('left') or love.keyboard.isDown('a') then
		self.x = self.x - self.speed/self.mass * dt
	end	
	
-- Jump
	if love.keyboard.isDown('up') or love.keyboard.isDown('w') then
 		if self.y_velocity == 0 then
			self.y_velocity = self.jump_height/math.max(self.mass/4, 1)
		end
	end	
	

    if self.y_velocity ~= 0 then
		self.y = self.y + self.y_velocity * dt
		self.y_velocity = self.y_velocity - self.gravity * dt 
    if self.y > self.ground then
		self.y_velocity = 0
    	self.y = self.groundground again.
	end	
end

function Player:draw()
	love.graphics.draw(self.img, math.round(self.x), math.round(self.y), self.angle, 1, 1, self.w/2, self.h/2)
end
```

**Comment by crysan** [comment]
So that the code worked through state-machine.
Thank!

**Comment by kyleconroy** [comment]
Sorry @crysan, but I'm not going to be able to help you in this case. I thought you might provide a  small example, but I don't have the time to port your large example to a state machine.

**Comment by crysan** [comment]
Hi!
Thanks for the answer. But I have found another library.
Have a good day!
