### ISSUE TITLE
Library not loading into Defold game engine

### ISSUE THREAD

**Issue by klaytonkowalski** [kyleconroy/lua-state-machine#22]
Hi, have the developers tried to add this library to a Defold project as a dependency? I'm able to attach other github releases on Defold, however for some reason this library doesn't load in.

**Comment by kyleconroy** [comment]
I'm not familiar with Defold. How does it load Lua from GitHub? When trying to load this repository, do you get any error messages?

**Comment by klaytonkowalski** [comment]
No errors messages, which is pretty strange. Here's a 3-second overview of how it loads Lua from GitHub: https://defold.com/manuals/libraries/

Like I've said, I use the same process for other Lua modules. In the meantime, I'll check if there's another way to import.

**Comment by kyleconroy** [comment]
I cut a new 2.0.0 release here (https://github.com/kyleconroy/lua-state-machine/releases/tag/2.0.0). Maybe that will work?

**Comment by klaytonkowalski** [comment]
Nope, didn't work. Maybe Defold requires some special files to be a part of the library or something. I looked into: https://github.com/britzl/cucumber-defold/releases (which is just a random lua module) and I see that it holds a game.project file, which is specific to Defold.

That's all right though, I can still download your source code manually and use it that way. When you set a github dependency in Defold, it actually downloads the source code from GitHub whenever you build and run your program, instead of holding the source code in the project folder itself.

Is it all right with you if I just download the file as a .lua and use it that way? It would then be distributed in the source files when I release the project.

**Comment by kyleconroy** [comment]
Yep! lua-state-machine is [MIT licensed](https://github.com/kyleconroy/lua-state-machine/blob/master/LICENSE) which means you can basically do whatever you want with the code. Good luck!
